name: Automatic pull request

on:
  push:
    branches:
      - MAIN  
jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Expose git commit data
        uses: rlespinasse/git-commit-data-action@v1

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.2.3
        with:
          branch: "MAIN"
          base: main
          title: "Automated PR"
           


